# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('image_1', models.CharField(max_length=200)),
                ('image_2', models.CharField(max_length=200)),
                ('image_3', models.CharField(max_length=200)),
                ('image_4', models.CharField(max_length=200)),
                ('image_5', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
                ('product_description', models.CharField(max_length=200)),
                ('wattage', models.CharField(max_length=20)),
                ('lumens', models.CharField(max_length=20)),
                ('lumens_per_watt', models.CharField(max_length=20)),
                ('cct', models.CharField(max_length=30)),
                ('cri', models.CharField(max_length=20)),
                ('dimensions', models.CharField(max_length=30)),
                ('colors', models.CharField(max_length=40)),
                ('life_span', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
                ('warranty', models.CharField(max_length=30)),
                ('replacement', models.CharField(max_length=30)),
                ('ul_certified', models.BooleanField(default=False)),
                ('dlc_certified', models.BooleanField(default=False)),
                ('isIndoor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
