# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
                ('product_description', models.CharField(max_length=200)),
                ('wattage', models.CharField(max_length=20)),
                ('lumens', models.CharField(max_length=20)),
                ('lumens_per_watt', models.CharField(max_length=20)),
                ('cct', models.CharField(max_length=30)),
                ('cri', models.CharField(max_length=20)),
                ('dimensions', models.CharField(max_length=30)),
                ('colors', models.CharField(max_length=40)),
                ('life_span', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
                ('warranty', models.CharField(max_length=30)),
                ('replacement', models.CharField(max_length=30)),
                ('ul_certified', models.BooleanField(default=False)),
                ('dlc_certified', models.BooleanField(default=False)),
            ],
        ),
    ]
