# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
