# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160630_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
