# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_product_isfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudie',
            name='testimony_quote',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
