# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_casestudie_testimony_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_product_1', models.CharField(max_length=100)),
                ('featured_product_2', models.CharField(max_length=100)),
                ('featured_product_3', models.CharField(max_length=100)),
                ('featured_product_4', models.CharField(max_length=100)),
                ('featured_product_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.AddField(
            model_name='casestudie',
            name='address_link',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudie',
            name='image_1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudie',
            name='image_2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudie',
            name='image_3',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudie',
            name='image_4',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudie',
            name='image_5',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudie',
            name='isAutomotive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudie',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudie',
            name='isIndustrial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudie',
            name='isInstitutional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudie',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='isOutdoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='life_span',
            field=models.CharField(max_length=25),
        ),
    ]
