# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_casestudies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseStudies',
            new_name='CaseStudie',
        ),
    ]
